// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCguJcjxNqwfUlUJQ5yVOI4pHSGH1bgLEg',
    appId: '1:784790544501:web:c82a79db8b27f87df8d83c',
    messagingSenderId: '784790544501',
    projectId: 'kids-b33a3',
    authDomain: 'kids-b33a3.firebaseapp.com',
    storageBucket: 'kids-b33a3.appspot.com',
    measurementId: 'G-M9T62PBLSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQ9edw7iwxMrc8uLpZkg4n1ynYvvJvU8',
    appId: '1:784790544501:android:78f51debd3f3e546f8d83c',
    messagingSenderId: '784790544501',
    projectId: 'kids-b33a3',
    storageBucket: 'kids-b33a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClhEDAtw3ZmANyVbhplXFEL16Zn6Ke8H4',
    appId: '1:784790544501:ios:e33f43d4b53d03aaf8d83c',
    messagingSenderId: '784790544501',
    projectId: 'kids-b33a3',
    storageBucket: 'kids-b33a3.appspot.com',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClhEDAtw3ZmANyVbhplXFEL16Zn6Ke8H4',
    appId: '1:784790544501:ios:ed07566da5926a65f8d83c',
    messagingSenderId: '784790544501',
    projectId: 'kids-b33a3',
    storageBucket: 'kids-b33a3.appspot.com',
    iosBundleId: 'com.example.game.RunnerTests',
  );
}
